// AUTOGENERATED by `just gen-api`. Do not edit.
// On first run after Phase 1, this file is regenerated from backend/openapi.json
// (produced by `python -m scripts.dump_openapi openapi.json`).
//
// The hand-written types in lib/api/documents.ts intentionally shadow this for
// readability while the API is small. Once the surface grows, components should
// switch to `import type { paths, components } from "./schema.gen"`.

export type paths = Record<string, never>;
export type components = { schemas: Record<string, never> };
